### ISSUE TITLE
Implementera get_hint API endpoint

### ISSUE THREAD

**Issue by JimOgren** [taleldayekh/sudoku-solver#13]

**Comment by JimOgren** [comment]
Hej @taleldayekh! Några funderingar kring hur jag strukturerar detta:

1. En ny metod `get_hint` i `Sudoku.py`. 
2. Sedan behöver vi ett till use-case, antingen i ny fil `use_cases/post_get_hint.py` alternativt att vi har alla post-metoder i ett use case? I `post_solve.py` definierar vi `class InvalidSudoku(Exception):` och den vill jag använda även i get_hint.
3. En ny endpoint I `sudoku_controller.py`:
```python
@sudoku_v1.route("/get_hint", methods=["POST"])
def get_hint_endpoint() -> Response:
```

4. So far so good. Men nu till testen. I `test_sudoku_controller.py`har vi
```python
@pytest.mark.usefixtures("api_server")
class TestSudokuPOST:
```

Antingen bör test av get_hint också finnas i samma klass? Tänker att alla POST-metoder är samlade? Eller så skapar vi två separata klasser 
```python
class TestSudokuSolvePOST
class TestSudokeGetHintPOST
```

Vad tycker du?

**Comment by taleldayekh** [comment]
Get hint är ett eget use case, även fast det också är en POST metod så är det korrekt att skapa en helt ny `post_get_hint.py` fil. Jag tycker du kan importera `class InvalidSudoku(Exception)` och använda den i `post_get_hint.py`. Egentligen kanske man skulle ha en egen gemensam fil för exceptions som heter `errors` eller något liknande, men importera den tillsvidare så kan vi alltid separera ut exceptions om nödvändigt senare.

Angående testen så hör de hemma i samma klass tycker jag. Det känns som en logisk uppdelning att ha alla POST-relaterade test för en controller fil i samma klass, alla GET-relaterade is samma klass osv:

```python
class TestSudokuPOST:
   def test_solve...

   def test hint...
```

Så länge vi inte har så många endpoints att det blir ohanterbart tycker jag denna uppdeling är ok.

Ett annat tips är att inte namnge endpoints som verb. Så `@sudoku_v1.route("/get_hint", methods=["POST"])` borde vara `@sudoku_v1.route("/hint", methods=["POST"])`. Verbet definieras av vilken request method som används, i.e `GET hint`, `POST hint`.

Googlade lite snabbt och hittade [denna korta artikel](https://hackernoon.com/restful-api-design-step-by-step-guide-2f2c9f9fcdbf) som ger en fingervisning om hur API endpoints ska struktureras.

**Comment by taleldayekh** [comment]
> 3. En ny endpoint I `sudoku_controller.py`:

Helt korrekt!
