### ISSUE TITLE
Add API endpoint for solving a sudoku

### ISSUE THREAD

**Issue by taleldayekh** [taleldayekh/sudoku-solver#15]
Implementera endpoint för att lösa en sudoku. Endpointen ska:
- Ta en ofullständig sudoku som input
- Ge en löst sudoku tillbaka som svar baserat på den ofullständiga sodukun
- Ge ett error-meddelande som svar ifall input inte är giltig sudoku data
- Ge ett error-meddelande som svar ifall sudokun inte går att lösa (är detta relevant?)
- Ge ett error-meddelande istället för att krascha servern ifall något oväntat sker, ex. Internal Server Error

@JimOgren är ovanstående vad vi vill?

**Comment by JimOgren** [comment]
@taleldayekh, det ser bra ut tycker jag! Jag tycker det är bra att ha två olika error: en för inkorrekt input och en för olösbar sudoku, alla fall tills vidare. Det kommer att vara relevant för när vi vill skanna sudoku med kamera längre fram.
