### ISSUE TITLE
Research server/api architecture

### ISSUE THREAD

**Issue by taleldayekh** [taleldayekh/sudoku-solver#2]
## Description

```
server/
├── app_sudoku/
│   ├── domain/
│   │   └── model.py
│   └── use-cases/
│       └── post_validate_sudoku.py
├── interfaces/
│   └── http/
│       └── sudoku/
│           └── sudoku_controller.py
└── tests/
    ├── unit/
    └── integration/
```

@JimOgren Har försökt komma fram till hur projektet kan organiseras i enlighet med olika lager. Så här har jag resonerat.

`app_sudoku` mappen representerar ett "business" område i appen. Ett annat framtida sådan område skulle exempelvis kunna vara `app-users` ifall vi har användare som registrerar sig etc.

Varje "område" har sitt eget "business logic layer" och "service layer". Allt som finns i `domain` mappen tillhör business logic lagret medan allt i `use-cases` mappen tillhör service lagret.

Utöver `app_sudoku` så har vi en `interfaces` mapp. Ett interface skulle kunna vara exempelvis en CLI eller webb app men i vårt fall är det API:n. `sudoku_controller.py` filen innehåller alla `GET`, `POST` o.s.v. requests som är relevanta för sudoku delen. Exempelvis skulle en endpoint kunna vara, `POST` `/sudoku/validate` eller `GET` `/sudoku/board`.

Hade vi implementerat användare så skulle de kunna höra hemma in en `users` mapp med en `users_controller.py` fil.

Tanken är att inget av de övriga lagren ska vara beroende av interfacet. Dvs. appen ska inte stå och falla med ifall vi använder Flask eller något annat.

Mellan interfaces lager och business logic lagret ligger services lagret (även kallat orchestration layer), i vårt fall `use-cases` mappen med `post_validate.py` filen.

När interfaces lagret får en request från användaren, ex. `GET /sudoku/validate` så går den till lämpligaste use case, ex. `post_validate.py` vilket i sin tur går till business lagret för sitt område (app-sudoku).

Som jag förstått detta så ger det oss en arkitektur där ett lager aldrig är beroende av lagret utanpå, utan beroende pekar alltid inåt.

```
Business Logic Layer <-- Services Layer <-- Interfaces Layer
```

Jag försöker fortfarande förstå dessa tankesätt och all jargong :). Om du har några övriga tankar så får du gärna organisera om eller ge annan input.

**Comment by JimOgren** [comment]
Intressant @taleldayekh! Skulle själva sudoku-klassen vara i `model.py`? Jag tänker att själva suduko-lösaren är en del av business layer eller har jag missförstått? Det tar tid att vänja sig vid detta tankesätt. Men jag tror det är värt att vi investerar tid i detta. Dels lär vis oss förhoppningsvis något och dels är det lättare att skala om man väl gjort rätt från början :)

**Comment by taleldayekh** [comment]
Du har helt rätt, sudoku lösaren hör hemma i `model.py`. Om du kollar [här](https://github.com/taleldayekh/sudoku-solver/blob/validation-api/server/app_sudoku/domain/model.py) så har jag flyttat över validations koden till `model.py`.

**Comment by taleldayekh** [comment]
Gjorde dessa anteckningar när jag försökte förstå `Domain Model`. I detta exempel skulle en `class` kunna vara `PlaySudoku` med `methods` som `provide_sudoku_board`, `give_sudoku_hint` etc.

<img width="764" alt="Screenshot 2020-12-09 at 22 22 38" src="https://user-images.githubusercontent.com/43838780/101689025-27e38300-3a6d-11eb-9f27-e0dbe22fffb7.png">

**Comment by JimOgren** [comment]
`provide_sudoku_board` skulle den metoden returnera en ny sudoku (antingen genom att hämta från hemsida eller ännu hellre generera) eller menas det att transformera en list of ints till en annan representation? 

Jag förstår tanken med att det ska vara en process. Spontant känns `PlaySudoku` som ett onaturligt namn? Det känns mer naturligt att klassen heter `sudoku` och vi skapar ett `sudoku`-objekt. Fast det handlar säkert bara om att jag inte är van att tänka i dessa banor.

**Comment by JimOgren** [comment]
När jag tänker efter mer så är nog `PlaySudoku` ett bra namn. Det beskriver mer vad som ska göras!

**Comment by taleldayekh** [comment]
`PlaySoduku` var bara något jag kom på när jag gjorde anteckningarna. Jag tror faktiskt att en `Sudoku` klass är bättre och snyggare än `PlaySoduku`. Så jag skulle nog köra på ditt första förslag. :)

**Comment by taleldayekh** [comment]
Vad gäller de olika metoderna i klassen så var de också bara något som jag kom på i stunden för att försöka illustrera tankegångarna.

**Comment by JimOgren** [comment]
Då förstår jag, låter bra! Då kör jag på `Sudoku` som klassnamn så länge -  det går ju alltid att ändra sen :)
