### ISSUE TITLE
Add generate sudoku API-endpoint

### ISSUE THREAD

**Issue by JimOgren** [taleldayekh/sudoku-solver#22]
@taleldayekh!

API-endpoint för generate_sudoku. Jag tänker att det blir en ny modul `use_cases/get_generate.py` och sedan en ny endpoint:
```python
@sudoku_v1.route("/generate", methods=["GET"])
def generate_endpoint() -> Response:
```

I första läget kan vi göra att den alltid genererar en "easy" och blir således en GET-request, eller hur? Längre fram kan vi ju göra en POST-request där man skickar önskad svårighetsgrad. 

Fler tankar?

**Comment by taleldayekh** [comment]
Jag tycker ditt förslag låter alldeles utmärkt så kör på det!
