### ISSUE TITLE
Add verify solution API endpoint

### ISSUE THREAD

**Issue by JimOgren** [taleldayekh/sudoku-solver#25]
En endpoint för att verifiera en lösning. Användaren har löst en sudoku via UI och vill kontrollera att lösningen hen inmatat är korrekt.

**Comment by JimOgren** [comment]
@taleldayekh Ska jag vänta med att implementera denna API till efter vi har gjort refactoring?

**Comment by taleldayekh** [comment]
Ja, det kanske blir bäst att vänta för att inte behöva ändra sedan. Jag antar att allt redan är löst och det bara är en fråga om att stoppa in koden på rätt plats. :)

**Comment by JimOgren** [comment]
Det låter klokast så! Det är ju en enkel grej att göra eftersom allt annat är på plats. Var mest att jag inte har något att koda för tillfället :P 

Men jag jobbar vidare med skanner-delen, har gjort några små test och framsteg. Får visa när vi hörs i helgen!
