### ISSUE TITLE
Refactor sudoku_utils.py

### ISSUE THREAD

**Issue by taleldayekh** [taleldayekh/sudoku-solver#26]
Fundera ut hur koden i `sudoku_utils.py` kan delas upp i förhållande till våra olika "domains".

**Comment by taleldayekh** [comment]
@JimOgren, vill dubbelkolla så att jag förstått rätt. Denna funktion returnerar alla nummer i en rad eller hur?

```python
def get_row(board: List[int], row: int) -> List[int]:
    return [board[row * NROWS + col] for col in range(NCOLS)]
```

**Comment by JimOgren** [comment]
Ja precis, alla siffror på rad `row`. Samma för `get_column` och `get_box`. `get_row_number` etc. returnerar vilken rad ett visst index tillhör.
