### ISSUE TITLE
Solve and display generated Sudoku

### ISSUE THREAD

**Issue by taleldayekh** [taleldayekh/sudoku-solver#35]
- [x] Skicka genererad sudoku till `solve` endpoint.
- [x] Rita upp löst sudoku i UI.

**Comment by taleldayekh** [comment]
@JimOgren Implementerade lite snabbt ovanstående, funkar fin fint. 😀

<img width="526" alt="Screenshot 2021-01-17 at 20 00 53" src="https://user-images.githubusercontent.com/43838780/104853099-f5943380-58fe-11eb-8176-a082e0cc7918.png">

**Comment by taleldayekh** [comment]
Gör ingen PR av detta utan avvaktar tills vi har etablerat en stabil arkitektur för app delen.

**Comment by JimOgren** [comment]
Snyggt @taleldayekh! Vad kul att det funkar och verkar ha gått rätt enkelt att fixa!
