### ISSUE TITLE
Read up on mobile app architecture

### ISSUE THREAD

**Issue by taleldayekh** [taleldayekh/sudoku-solver#37]
Bestäm arkitektur för app, exempelvis, MVVM eller MVC.

**Comment by taleldayekh** [comment]
@JimOgren Sudoku från "View" i MVVM.
<img width="563" alt="Screenshot 2021-01-28 at 21 31 46" src="https://user-images.githubusercontent.com/43838780/106195774-eb045480-61b0-11eb-9d74-01a8b8a36460.png">

**Comment by JimOgren** [comment]
Snyggt! Så kul att se :)
