### ISSUE TITLE
Adding solver to sudoku module

### ISSUE THREAD

**Issue by JimOgren** [taleldayekh/sudoku-solver#4]
Implement a solver

**Comment by JimOgren** [comment]
Jag har en idé om hur den ska implementeras. En "list of ints" som input kommer transformeras till en hash map av strings innan lösning. Samtidigt som denna transformation görs så kollas om input faktiskt är en giltig sudoku. Då kommer alltid denna transformation samt kontroll göras. Några av de tidigare funktionerna kommer kunna tas bort.

**Comment by JimOgren** [comment]
@taleldayekh, jag har implementerat lösaren och strukturerat om lite nu. Behöver lägga till några test men tänkte göra en PR i helgen. Ska jag vänta till du har gjort omstrukturering för API? Eller ska jag köra upp det här så fort det är klart?

**Comment by taleldayekh** [comment]
Tror att vi kommer få merge conflict eftersom vi arbetat på samma filer. Jag skulle kunna öppna en PR med det jag har nu och när det är mergat så kan du dra den koden och lägga till dina ändringar och sedan öppna din PR. Vad tror du om det?

**Comment by JimOgren** [comment]
Ja så kan vi göra! Kör din PR först (ingen stress) och sedan lägger jag till mina ändringar efter det.

**Comment by JimOgren** [comment]
@taleldayekh, nu har jag börjat implementera lösaren i den uppdaterade versionen av `develop`. Får se hur långt jag hinner i morgon. Ska vi köra möte igen på söndag kl 10? :)

**Comment by taleldayekh** [comment]
Nice! Javisst, låt oss säga söndag kl 10.
