### ISSUE TITLE
Sketch app user flow

### ISSUE THREAD

**Issue by taleldayekh** [taleldayekh/sudoku-solver#42]
- [x] Samla inspiration från andra sudoku appar
- [x] Gör ett första förslag user-flow diagram

**Comment by taleldayekh** [comment]
@JimOgren Ett första user flow diagram vi kan diskutera imorgon.

![User Flow_Sudoku](https://user-images.githubusercontent.com/43838780/109399874-ba494380-7945-11eb-8557-d4b36177cfbd.png)

**Comment by JimOgren** [comment]
Väldigt snygg sketch! Ser bra ut, känns som att mesta av funktionaliteten är där men att man inte behöver bygga allt direkt. User-delen kan man t.ex. lägga till senare. 

Jag tror idén att få poäng och samla poäng är ett bra sätt att göra appen roligare att använda! En tanke som slog mig nu är att man kan få poäng utifrån svårighetsgrad men också tid det tar att lösa den. Eller att de olika svårighetsgraderna ger viss poäng och sedan får man fler bonuspoäng beroende på hur snabbt man löser. Då finns det två utmaningar: en att kunna lösa de svåraste sudoku och en kunna lösa enkla sudoku men på kortast tid.
