### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by JimOgren** [taleldayekh/sudoku-solver#49]
Hej @taleldayekh!

När vi byggde appen på min dator i söndags installerade vi några extra dependencies. Därför har jag ändringar i `package.json` och `yarn.lock`. Exempelvis, "@react-native-community/cli": "^5.0.1-alpha.2" och "react-native-eject": "^0.1.2". 

Vad blev slutsatsen, behövs dessa ändringar? Ska jag lägga till dessa i repo eller klarar vi oss utan dessa dependencies?

**Comment by taleldayekh** [comment]
De borde inte behövas, vi installerade dem för att generera nya iOS och Android mappar. Nu när de väl är på plats lokalt för dig så kan vi nog skippa att lägga till dessa dependencies i `package.json`.

**Comment by JimOgren** [comment]
Perfa! Det var lite så jag tänkte också och vi vill ju undvika onödiga dependencies.
