### ISSUE TITLE
Implement sudoku.py as class?

### ISSUE THREAD

**Issue by JimOgren** [taleldayekh/sudoku-solver#5]
Jag tänkte lite kring detta! På många sätt vore det naturligt att implementera en sudokuklass. I API, när input skickas så skapas ett sudoku-objekt som sedan håller list of ints och sedan en transformerad representation, hint och lösning. När den API har skickat tillbaka request så kan objektet raderas, det blir ett naturligt sätt att hantera minne. Eller vad tror du @taleldayekh? Det finns säker andra sätt att lösa det på också. Jag tänker att jag först implementerar den funktionalitet vi vill ha i sudoku.py och sedan kan vi skriva det som en klass senare om vi tror det blir bättre.

**Comment by taleldayekh** [comment]
Det låter väldigt bra tycker jag! Kör på det. Tror också att det passar bättre med en Sudoku klass.

Jag har strukturerat om projektet baserat på de olika lagren, "business logic layer", "interface layer", etc. Jag ska ta och sammanfatta mitt resonemang kring det imorgon och dela ~~här~~, i issue #2 .
