### ISSUE TITLE
Running flask app does not work

### ISSUE THREAD

**Issue by JimOgren** [taleldayekh/sudoku-solver#9]
Hej @taleldayekh! 

Jag kanske gör något fel när jag försöker starta serve-api? För mig fungerar inte `make serve-api` [ska det inte stå server-api?] Men detta verkar vara utanför pipenv? Jag har inte flask installerat globalt och den förstår inte kommandot. Men även när jag försöker starta servern genom `pipenv run python -m flask run` så fungerar det inte. Borde inte `FLASK_APP` peka till `app.py`? Det vill säga i `.flaskenv` bordet det stå `FLASK_APP=server/app.py? `?

**Comment by JimOgren** [comment]
Insåg att `FLASK_APP=server` fungerar fint. Problemet är att den inte läser in `.flaskenv`. Men det vore önskvärt att i Makefile köra genom pipenv eller vad tycker du?

**Comment by JimOgren** [comment]
Ah, jag glömde igen att lägga till `--dev` till `pipenv install`. Då fungerar `.flaskenv`.

Men mitt förslag är att i alla fall ändra från `flask run` till `pipenv run python -m flask run` i Makefile :)

**Comment by taleldayekh** [comment]
Visst, ändra till det kommandot, inga problem 👍🏼
